development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: harvestman_development
  pool: 5
  username: harvestman
  password: password

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: harvestman_test
  pool: 5
  username: harvestman
  password: password
